### ISSUE TITLE
[Need advice] -ер, -ёр when latinizing/transliterating

### ISSUE THREAD

**Issue by Sonotoki-da** [dima74/Wikipedia-Yofication#40]
Hello! Sorry to bother you with my problem. If at all possible, I'd like your advice on something.

I'm writing a latinizer/cyrillizer in C for the Uzbek language. Most words with -ер, -ёр suffixes in Uzbek are directly derived from Russian. For example: стажер, режиссер, партнер, which should be written with -ёр.

Typical users can't be bothered with this reality, so we as developers should take up the challenge to make our lives easier. The latinizer part of my code easily converts ё to yo, but it can't do that so with, say, режиссер. Because currently режиссер -> rejisser (should be rejissyor). And, of course, most users don't use ё most of the time.

I've done some research and I've found out that this yofication thing can't be fully automated because of the contextual differences. But even then, with tools like the one you wrote, we can do something about it.

So I wanted to ask, if you wrote the main part of yoficator with Rust, can we use it as a server? I have set up my server to use shared memory with ring buffers between my Python clients.

I'm not familiar with Rust at all and there is no documentation on how your program works so I can write my own yoficator in C based on that. I chose your repo because it looks up-to-date.

Thank you!

**Comment by dima74** [comment]
Hi! I would recommend using this program as a binary. To do so:

* [Install `Rust`](https://www.rust-lang.org/learn/get-started):
```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

* Build the program:
```
cargo build --release --bin yoficate-text
```

* Run the program. At the startup it will download yofication data from the github.
```
./target/release/yoficate-text
```

* Now use the program. It will read stdin line by line, Each line is new request for text yofication, and should be in the JSON format `{"text": "..."}`. As a response, program will output yoficated text in the same JSON format. It is recommended to start program once and use it for multiple requests.

Please ask if you have any questions

**Comment by Sonotoki-da** [comment]
Thank you so much! I knew there was a feasible solution for this!
